# Generated by Django 3.2.5 on 2021-08-29 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtubeimage', models.ImageField(upload_to='ChannelPic')),
                ('channel_name', models.CharField(max_length=100)),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subs', to=settings.AUTH_USER_MODEL)),
                ('youtuber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_thumbnail', models.ImageField(upload_to='thumbnails')),
                ('video_title', models.CharField(max_length=255)),
                ('video_desc', models.TextField()),
                ('video', models.FileField(upload_to='videos')),
                ('Views', models.IntegerField()),
                ('youtuber_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubeapp.youtuber')),
            ],
        ),
    ]
