# Generated by Django 3.2.5 on 2021-08-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0002_alter_video_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
