# Generated by Django 3.2.5 on 2021-08-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0002_auto_20210816_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_thumbnail', models.ImageField(upload_to='thumbnails')),
                ('video_title', models.CharField(max_length=255)),
                ('video_desc', models.TextField()),
                ('video', models.FileField(upload_to='videos')),
                ('youtuber_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubeapp.youtuber')),
            ],
        ),
    ]
